#!/usr/bin/env python
"""
$Id$

Enums required for Maelstrom
"""

# Attack enums
ATTACK_MISSED = 0
ATTACK_BLOCKED = 1
ATTACK_BLOCKED_CRITICAL = 2
ATTACK_ABSORBED = 3		# For armour absorbtion or mercenary absorbtion
ATTACK_BLUDGEON = 4
ATTACK_BLUDGEON_WOUND = 5
ATTACK_BODGE = 6
ATTACK_HIT = 7
ATTACK_HIT_SERIOUS = 7
ATTACK_HIT_CRITICAL = 8
ATTACK_HIT_MAGIC = 10
ATTACK_DEFENDER_BODGE = 11

# Damage enums
DAMAGE_BLUDGEONING = 0
DAMAGE_SERIOUS = 1

